import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/app/components/NavBar";
import { AuthProvider } from "./context/AuthContext";
import { Box, CssBaseline } from "@mui/material";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Webskitter Assignment App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Box sx={{ background: "#ddd", minHeight: "100vh", color: "black" }}>
          <AuthProvider>
            <CssBaseline />
            <NavBar />
            {children}
          </AuthProvider>
        </Box>
      </body>
    </html>
  );
}
